In [1]:

import sys
import os
import importlib
import numpy as np

In [2]:
fieldDict = dict.fromkeys([11, 12, 13, 14])

fieldDict[11] = {'bmi': (1533, 1536), 'weight': (1475, 1484),'income':(124, 125),'education':122}
fieldDict[12] = {'bmi': (1644, 1647), 'weight': (1449, 1458),'income':(116, 117),'education':114}
fieldDict[13] = {'bmi': (2192, 2195), 'weight': (1953, 1962),'income':(152, 153),'education':150}
fieldDict[14] = {'bmi': (2247, 2250), 'weight': (2007, 2016),'income':(152, 153),'education':150}


In [3]:
for year in fieldDict:
    print(year, fieldDict[year])




11 {'bmi': (1533, 1536), 'weight': (1475, 1484), 'income': (124, 125), 'education': 122}
12 {'bmi': (1644, 1647), 'weight': (1449, 1458), 'income': (116, 117), 'education': 114}
13 {'bmi': (2192, 2195), 'weight': (1953, 1962), 'income': (152, 153), 'education': 150}
14 {'bmi': (2247, 2250), 'weight': (2007, 2016), 'income': (152, 153), 'education': 150}


In [4]:
def getIncome(incomeString):
    if incomeString != '  ':
        income = int(incomeString)
    else:
        income = 9
    return income



In [5]:
 def getEducation(educationString):
        if educationString != ' ':
            education = int(educationString)
        else:
            education = 9
        return education


In [6]:
def convertBMI(bmiString, shortYear):
    bmi = 0
    if shortYear == 0 and bmiString != '999':
        bmi = .1 * float(bmiString)
    elif shortYear == 1 and bmiString != '999999':
        bmi = .0001 * float(bmiString)
    elif 2 <= shortYear <= 10 and bmiString != '9999':
        bmi = .01 * float(bmiString)
    elif shortYear > 10 and bmiString != '    ':
        bmi = .01 * float(bmiString)
    return bmi

In [1]:
path = r'/Users/amin/Desktop/data science/exercise 3.6/data'
fileList = os.listdir(path)
for filename in fileList:
    try:
        shortYear = int(filename[6:8])
        if 14 <shortYear or  shortYear < 11:
            1/0
        year = 2000 + shortYear
        file = path + filename
        fields = fieldDict[2000+shortYear]
        file = path + '/' + filename
        q=4
        n=0
        A = np.zeros(shape=(q, q))
        X=np.zeros(shape = (10000,3))
        sInc, eInc = fields['income']
        sBMI, eBMI = fields['bmi']
        fEduc = fields['education']
        with open(file, 'r', encoding='latin-1') as f:
            for record in f:
                incomeString = record[sInc-1:eInc]
                income = getIncome(incomeString)

                bmiString = record[sBMI-1:eBMI]
                bmi = convertBMI(bmiString, year)
                education = getEducation(record[fEduc-1])
                
                if education < 9 and income < 9 and 0 < bmi < 99:
                    w = np.matrix([1,income,bmi,education]).T
                    A += w*w.T
                    n = int(A[0,0]) # Number of valid observations

                if n % 10000 == 0:
                    M = A[1:,1:]
                    mean = np.matrix(A[1:,0]/n).T
                    SigmaHat = M/n - mean*mean.T

                    # Extract the diagonal from S and
                    s = np.sqrt(np.diag(SigmaHat))
                    # compute the square roots.
                    # Create a diagonal matrix.
                    D = np.diag(1/s)
                if int(n) <= 10000:
                    # print(n)
                    col = w[1:]

                    X[n-1,:] = col.reshape((3,))
                    # print
                    # return
            np.savetxt(f'./X{shortYear}.txt',X,fmt='%5.2f')
              
    except(ValueError, ZeroDivisionError):
        pass

NameError: name 'os' is not defined

In [8]:
#

In [9]:

X=np.loadtxt('../X11.txt')


In [10]:

np.var(X,axis=0)

array([ 5.23154599, 38.84495905,  5.23154599])

In [11]:
np.corrcoef(X,rowvar=False)

array([[ 1.        , -0.10276998,  1.        ],
       [-0.10276998,  1.        , -0.10276998],
       [ 1.        , -0.10276998,  1.        ]])

In [12]:
print(R)

[[ 1.         -0.08533416  0.45790145]
 [-0.08533416  1.         -0.09695461]
 [ 0.45790145 -0.09695461  1.        ]]
